const shopActionType = {
  FETCH_COLLETCIONS_START: 'FETCH_COLLETCIONS_START',
  FETCH_COLLETCIONS_SUCCESS: 'FETCH_COLLETCIONS_SUCCESS',
  FETCH_COLLETCIONS_FAIL: 'FETCH_COLLETCIONS_FAIL' 
}

export default shopActionType;
